import {
  ContentZoneTemplate,
  ContributionSlotDefinition,
  DecorationElement,
  MasterTemplate,
  PresentationTrackOption,
  PublishingDocument,
  TextRun,
} from '@/types/publishing';

const now = () => new Date().toISOString();
export const FONT_NANUM_SQUARE_REGULAR = 'NanumSquare';
export const FONT_NANUM_SQUARE_BOLD = 'NanumSquareBold';
export const FONT_NANUM_SQUARE_EXTRABOLD = 'NanumSquareExtraBold';

export const DEFAULT_PRESENTATION_TRACKS: PresentationTrackOption[] = [
  { id: 'oral-o1', kind: 'oral', prefix: 'O1', label: 'Facial Deformity', glmHints: ['O1.Facial Deformity', 'Facial Deformity'] },
  { id: 'oral-o2', kind: 'oral', prefix: 'O2', label: 'Oral Cancer & Reconstruction', glmHints: ['O2.Oral Cancer & Reconstruction', 'Oral Cancer & Reconstruction'] },
  { id: 'oral-o3', kind: 'oral', prefix: 'O3', label: 'Oral Disease & Others', glmHints: ['O3.Oral Disease & Others', 'Oral Disease & Others'] },
  { id: 'oral-o4', kind: 'oral', prefix: 'O4', label: 'Dental Implant', glmHints: ['O4.Dental Implant', 'Dental Implant'] },
  { id: 'oral-o5', kind: 'oral', prefix: 'O5', label: 'TMJ', glmHints: ['O5.TMJ', 'TMJ'] },
  { id: 'oral-o6', kind: 'oral', prefix: 'O6', label: 'Trauma & Dentoalveolar Surgery', glmHints: ['O6.Trauma & Dentoalveolar Surgery', 'Trauma & Dentoalveolar Surgery'] },
  { id: 'poster-p1', kind: 'poster', prefix: 'P1', label: 'Oral Cancer & Pathology', glmHints: ['P1.Oral Cancer & Pathology', 'Oral Cancer & Pathology'] },
  { id: 'poster-p2', kind: 'poster', prefix: 'P2', label: 'Trauma & Dentoalveolar Surgery', glmHints: ['P2.Trauma & Dentoalveolar Surgery', 'Trauma & Dentoalveolar Surgery'] },
  { id: 'poster-p3', kind: 'poster', prefix: 'P3', label: 'Dental Implant', glmHints: ['P3.Dental Implant', 'Dental Implant'] },
  { id: 'poster-p4', kind: 'poster', prefix: 'P4', label: 'Orthognathic & Esthetic Surgery', glmHints: ['P4.Orthognathic & Esthetic Surgery', 'Orthognathic & Esthetic Surgery'] },
  { id: 'poster-p5', kind: 'poster', prefix: 'P5', label: 'Tissue Engineering & Reconstruction', glmHints: ['P5.Tissue Engineering & Reconstruction', 'Tissue Engineering & Reconstruction'] },
  { id: 'poster-p6', kind: 'poster', prefix: 'P6', label: 'TMJ & Cleft Lip Palate', glmHints: ['P6.TMJ & Cleft Lip Palate', 'TMJ & Cleft Lip Palate'] },
  { id: 'poster-p7', kind: 'poster', prefix: 'P7', label: 'Infection & Others', glmHints: ['P7.Infection & Others', 'Infection & Others'] },
];

const SPEAKER_THREAD_SLOT_SCHEMA: ContributionSlotDefinition[] = [
  { slotKey: 'track', label: '세션/트랙', role: 'subheading', language: 'mixed' },
  { slotKey: 'title_ko', label: '국문 제목', role: 'title', language: 'ko' },
  { slotKey: 'authors_ko', label: '국문 저자', role: 'paragraph', language: 'ko' },
  { slotKey: 'affiliation_ko', label: '국문 소속', role: 'paragraph', language: 'ko' },
  { slotKey: 'body_ko', label: '국문 본문', role: 'paragraph', language: 'ko', allowOverflow: true },
  { slotKey: 'title_en', label: '영문 제목', role: 'heading', language: 'en' },
  { slotKey: 'authors_en', label: '영문 저자', role: 'paragraph', language: 'en' },
  { slotKey: 'affiliation_en', label: '영문 소속', role: 'paragraph', language: 'en' },
  { slotKey: 'body_en', label: '영문 본문', role: 'paragraph', language: 'en', allowOverflow: true },
];

export const A4_VERTICAL_PRESET = {
  key: 'A4_VERTICAL' as const,
  widthPx: 794,
  heightPx: 1123,
  widthMm: 210,
  heightMm: 297,
  dpi: 96,
  bleedMm: 0,
  safeMarginPx: {
    top: 48,
    right: 48,
    bottom: 48,
    left: 48,
  },
};

export const createMainBodyZone = (): ContentZoneTemplate => ({
  id: 'body_main',
  name: 'Main Text Flow',
  slotKey: 'body',
  kind: 'text-flow',
  locked: false,
  scope: 'template-fixed',
  allowOverflowSource: true,
  flowGroupId: 'body_flow',
  flowOrder: 1,
  allowThreadContinuation: true,
  frame: {
    x: 72,
    y: 96,
    width: 650,
    height: 900,
  },
  style: {
    fontFamily: 'Noto Serif KR',
    fontSize: 14,
    fontWeight: 400,
    lineHeight: 1.8,
    letterSpacing: 0,
    textAlign: 'justify',
    color: '#222222',
  },
  constraints: {
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    widowLines: 2,
    orphanLines: 2,
    verticalAlign: 'top',
  },
});

export const createImageZone = (name = 'Image Zone'): ContentZoneTemplate => ({
  id: 'image_zone',
  name,
  slotKey: 'image',
  kind: 'media-freeform',
  locked: false,
  scope: 'template-fixed',
  allowOverflowSource: false,
  frame: {
    x: 72,
    y: 96,
    width: 260,
    height: 220,
  },
  style: {
    fontFamily: 'Noto Serif KR',
    fontSize: 12,
    fontWeight: 400,
    lineHeight: 1.4,
    letterSpacing: 0,
    textAlign: 'center',
    color: '#475569',
  },
  constraints: {
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    verticalAlign: 'middle',
  },
});

export const createCoverZone = (): ContentZoneTemplate => ({
  id: 'cover_title_zone',
  name: 'Cover Title Zone',
  slotKey: 'title',
  kind: 'text-flow',
  locked: false,
  scope: 'template-fixed',
  allowOverflowSource: true,
  flowGroupId: 'cover_flow',
  flowOrder: 1,
  allowThreadContinuation: false,
  frame: {
    x: 72,
    y: 220,
    width: 650,
    height: 220,
  },
  style: {
    fontFamily: 'Noto Serif KR',
    fontSize: 30,
    fontWeight: 700,
    lineHeight: 1.4,
    letterSpacing: -0.2,
    textAlign: 'center',
    color: '#111111',
  },
  constraints: {
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    verticalAlign: 'middle',
  },
});

export const createSectionLeadZones = (): ContentZoneTemplate[] => [
  {
    id: 'section_lead_header',
    name: 'Section Lead Header',
    slotKey: 'section_title',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'section_lead_header',
    flowOrder: 1,
    allowThreadContinuation: false,
    frame: {
      x: 72,
      y: 140,
      width: 650,
      height: 180,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 24,
      fontWeight: 700,
      lineHeight: 1.45,
      letterSpacing: -0.2,
      textAlign: 'left',
      color: '#111111',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'middle',
    },
  },
  {
    id: 'section_lead_body',
    name: 'Section Lead Body',
    slotKey: 'body',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'section_lead_body',
    flowOrder: 1,
    allowThreadContinuation: true,
    frame: {
      x: 72,
      y: 380,
      width: 650,
      height: 616,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 1.8,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
];

export const createCoverPresetDecorations = (): DecorationElement[] => [
  {
    id: 'cover_title_label',
    type: 'text',
    locked: false,
    scope: 'template-fixed',
    x: 72,
    y: 130,
    width: 650,
    height: 40,
    text: 'Cover',
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 14,
      fontWeight: 700,
      lineHeight: 1.4,
      letterSpacing: 2,
      textAlign: 'center',
      color: '#64748b',
    },
  },
  {
    id: 'cover_title_binding',
    type: 'text',
    locked: false,
    scope: 'template-fixed',
    x: 72,
    y: 470,
    width: 650,
    height: 60,
    textBinding: 'document.title',
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 16,
      fontWeight: 500,
      lineHeight: 1.5,
      letterSpacing: 0.4,
      textAlign: 'center',
      color: '#475569',
    },
  },
  {
    id: 'cover_divider',
    type: 'shape',
    locked: false,
    scope: 'template-fixed',
    x: 247,
    y: 182,
    width: 300,
    height: 2,
    shape: 'line',
    fill: '#cbd5e1',
  },
];

export const createSectionLeadPresetDecorations = (): DecorationElement[] => [
  {
    id: 'section_lead_kicker',
    type: 'text',
    locked: false,
    scope: 'template-fixed',
    x: 72,
    y: 92,
    width: 220,
    height: 26,
    text: 'Section Opening',
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 12,
      fontWeight: 700,
      lineHeight: 1.4,
      letterSpacing: 1.8,
      textAlign: 'left',
      color: '#0f172a',
    },
  },
  {
    id: 'section_lead_divider',
    type: 'shape',
    locked: false,
    scope: 'template-fixed',
    x: 72,
    y: 338,
    width: 650,
    height: 2,
    shape: 'line',
    fill: '#cbd5e1',
  },
  {
    id: 'section_lead_number',
    type: 'text',
    locked: false,
    scope: 'template-fixed',
    x: 640,
    y: 92,
    width: 82,
    height: 32,
    textBinding: 'section.number',
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 24,
      fontWeight: 700,
      lineHeight: 1.2,
      letterSpacing: 0,
      textAlign: 'right',
      color: '#94a3b8',
    },
  },
];

export const createTwoColumnZones = (): ContentZoneTemplate[] => [
  {
    id: 'body_col_left',
    name: 'Left Column',
    slotKey: 'body',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'two_col_body',
    flowOrder: 1,
    allowThreadContinuation: true,
    frame: {
      x: 72,
      y: 96,
      width: 305,
      height: 900,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 13,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
  {
    id: 'body_col_right',
    name: 'Right Column',
    slotKey: 'body',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'two_col_body',
    flowOrder: 2,
    allowThreadContinuation: true,
    frame: {
      x: 417,
      y: 96,
      width: 305,
      height: 900,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 13,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
];

export const createPosterSummaryZones = (): ContentZoneTemplate[] => [
  {
    id: 'poster_summary_top',
    name: 'Poster Summary',
    slotKey: 'summary',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'poster_summary',
    flowOrder: 1,
    allowThreadContinuation: false,
    frame: {
      x: 72,
      y: 96,
      width: 650,
      height: 220,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 15,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
  {
    id: 'poster_summary_left',
    name: 'Poster Left',
    slotKey: 'body',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'poster_body',
    flowOrder: 1,
    allowThreadContinuation: true,
    frame: {
      x: 72,
      y: 350,
      width: 305,
      height: 646,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 13,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
  {
    id: 'poster_summary_right',
    name: 'Poster Right',
    slotKey: 'body',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'poster_body',
    flowOrder: 2,
    allowThreadContinuation: true,
    frame: {
      x: 417,
      y: 350,
      width: 305,
      height: 646,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 13,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
];

export const createPresentationTwoColumnZones = (): ContentZoneTemplate[] => [
  {
    id: 'presentation_intro',
    name: 'Presentation Intro',
    slotKey: 'summary',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'presentation_intro',
    flowOrder: 1,
    allowThreadContinuation: false,
    frame: {
      x: 72,
      y: 96,
      width: 650,
      height: 150,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 1.7,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
  ...createTwoColumnZones().map((zone, index) => ({
    ...zone,
    id: index === 0 ? 'presentation_left' : 'presentation_right',
    name: index === 0 ? 'Presentation Left' : 'Presentation Right',
    flowGroupId: 'presentation_body',
    flowOrder: index + 1,
    frame: {
      ...zone.frame,
      y: 280,
      height: 716,
    },
  })),
];

export const createSpeakerThreadZones = (): ContentZoneTemplate[] => [
  {
    id: 'speaker_track',
    name: 'Speaker Track',
    slotKey: 'track',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: false,
    flowGroupId: 'speaker_frontmatter_track',
    flowOrder: 1,
    allowThreadContinuation: false,
    frame: { x: 72, y: 82, width: 650, height: 26 },
    style: {
      fontFamily: FONT_NANUM_SQUARE_BOLD,
      fontSize: 10,
      fontWeight: 700,
      lineHeight: 1.4,
      letterSpacing: 0,
      textAlign: 'left',
      color: '#475569',
    },
    constraints: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, verticalAlign: 'middle' },
  },
  {
    id: 'speaker_title_ko',
    name: 'Korean Title',
    slotKey: 'title_ko',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: false,
    flowGroupId: 'speaker_frontmatter_ko',
    flowOrder: 1,
    allowThreadContinuation: false,
    frame: { x: 72, y: 126, width: 650, height: 78 },
    style: {
      fontFamily: FONT_NANUM_SQUARE_EXTRABOLD,
      fontSize: 13,
      fontWeight: 800,
      lineHeight: 1.4,
      letterSpacing: 0,
      textAlign: 'center',
      color: '#111111',
    },
    constraints: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, verticalAlign: 'top' },
  },
  {
    id: 'speaker_authors_ko',
    name: 'Korean Authors',
    slotKey: 'authors_ko',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: false,
    flowGroupId: 'speaker_frontmatter_ko',
    flowOrder: 2,
    allowThreadContinuation: false,
    frame: { x: 72, y: 218, width: 650, height: 28 },
    style: {
      fontFamily: FONT_NANUM_SQUARE_BOLD,
      fontSize: 12,
      fontWeight: 700,
      lineHeight: 1.5,
      letterSpacing: 0,
      textAlign: 'center',
      color: '#0f172a',
    },
    constraints: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, verticalAlign: 'middle' },
  },
  {
    id: 'speaker_affiliation_ko',
    name: 'Korean Affiliation',
    slotKey: 'affiliation_ko',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: false,
    flowGroupId: 'speaker_frontmatter_ko',
    flowOrder: 3,
    allowThreadContinuation: false,
    frame: { x: 72, y: 256, width: 650, height: 28 },
    style: {
      fontFamily: FONT_NANUM_SQUARE_REGULAR,
      fontSize: 10,
      fontWeight: 400,
      lineHeight: 1.45,
      letterSpacing: 0,
      textAlign: 'center',
      color: '#475569',
    },
    constraints: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, verticalAlign: 'middle' },
  },
  {
    id: 'speaker_body_ko',
    name: 'Korean Body',
    slotKey: 'body_ko',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'speaker_body_ko',
    flowOrder: 1,
    allowThreadContinuation: true,
    frame: { x: 72, y: 328, width: 650, height: 668 },
    style: {
      fontFamily: FONT_NANUM_SQUARE_REGULAR,
      fontSize: 10,
      fontWeight: 400,
      lineHeight: 1.2,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, widowLines: 2, orphanLines: 2, verticalAlign: 'top' },
  },
  {
    id: 'speaker_title_en',
    name: 'English Title',
    slotKey: 'title_en',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: false,
    flowGroupId: 'speaker_frontmatter_en',
    flowOrder: 1,
    allowThreadContinuation: false,
    frame: { x: 72, y: 126, width: 650, height: 78 },
    style: {
      fontFamily: FONT_NANUM_SQUARE_EXTRABOLD,
      fontSize: 13,
      fontWeight: 800,
      lineHeight: 1.4,
      letterSpacing: 0,
      textAlign: 'center',
      color: '#111111',
    },
    constraints: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, verticalAlign: 'top' },
  },
  {
    id: 'speaker_authors_en',
    name: 'English Authors',
    slotKey: 'authors_en',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: false,
    flowGroupId: 'speaker_frontmatter_en',
    flowOrder: 2,
    allowThreadContinuation: false,
    frame: { x: 72, y: 218, width: 650, height: 28 },
    style: {
      fontFamily: FONT_NANUM_SQUARE_BOLD,
      fontSize: 12,
      fontWeight: 700,
      lineHeight: 1.5,
      letterSpacing: 0,
      textAlign: 'center',
      color: '#0f172a',
    },
    constraints: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, verticalAlign: 'middle' },
  },
  {
    id: 'speaker_affiliation_en',
    name: 'English Affiliation',
    slotKey: 'affiliation_en',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: false,
    flowGroupId: 'speaker_frontmatter_en',
    flowOrder: 3,
    allowThreadContinuation: false,
    frame: { x: 72, y: 256, width: 650, height: 28 },
    style: {
      fontFamily: FONT_NANUM_SQUARE_REGULAR,
      fontSize: 10,
      fontWeight: 400,
      lineHeight: 1.45,
      letterSpacing: 0,
      textAlign: 'center',
      color: '#475569',
    },
    constraints: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, verticalAlign: 'middle' },
  },
  {
    id: 'speaker_body_en',
    name: 'English Body',
    slotKey: 'body_en',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'speaker_body_en',
    flowOrder: 1,
    allowThreadContinuation: true,
    frame: { x: 72, y: 328, width: 650, height: 668 },
    style: {
      fontFamily: FONT_NANUM_SQUARE_REGULAR,
      fontSize: 10,
      fontWeight: 400,
      lineHeight: 1.2,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, widowLines: 2, orphanLines: 2, verticalAlign: 'top' },
  },
];

export const createDefaultMasters = (): MasterTemplate[] => [
  {
    id: 'master_cover',
    name: 'Cover Master',
    scope: 'global',
    locked: true,
    background: {
      fill: '#ffffff',
      image: null,
    },
    decorations: [
      {
        id: 'cover_page_number',
        type: 'text',
        locked: true,
        scope: 'global-fixed',
        x: 372,
        y: 1072,
        width: 50,
        height: 20,
        textBinding: 'page.number',
      },
    ],
    contentZones: [createCoverZone()],
  },
  {
    id: 'master_body',
    name: 'Body Master',
    scope: 'global',
    mode: 'page-freeform',
    locked: true,
    background: {
      fill: '#ffffff',
      image: null,
    },
    decorations: [
      {
        id: 'header_line',
        type: 'shape',
        locked: true,
        scope: 'global-fixed',
        x: 48,
        y: 48,
        width: 698,
        height: 1,
        shape: 'line',
        fill: '#d0d0d0',
      },
      {
        id: 'body_page_number',
        type: 'text',
        locked: true,
        scope: 'global-fixed',
        x: 372,
        y: 1072,
        width: 50,
        height: 20,
        textBinding: 'page.number',
      },
    ],
    contentZones: [createMainBodyZone()],
  },
  {
    id: 'master_two_column',
    name: 'Two Column Master',
    scope: 'global',
    mode: 'page-freeform',
    locked: true,
    background: {
      fill: '#ffffff',
      image: null,
    },
    decorations: [
      {
        id: 'two_column_header_line',
        type: 'shape',
        locked: true,
        scope: 'global-fixed',
        x: 48,
        y: 48,
        width: 698,
        height: 1,
        shape: 'line',
        fill: '#d0d0d0',
      },
      {
        id: 'two_column_page_number',
        type: 'text',
        locked: true,
        scope: 'global-fixed',
        x: 372,
        y: 1072,
        width: 50,
        height: 20,
        textBinding: 'page.number',
      },
    ],
    contentZones: createTwoColumnZones(),
  },
  {
    id: 'master_speaker_thread',
    name: 'Speaker Thread Master',
    scope: 'global',
    mode: 'speaker-thread',
    usesPresentationTracks: true,
    locked: true,
    background: {
      fill: '#ffffff',
      image: null,
    },
    decorations: [
      {
        id: 'speaker_thread_presentation_code',
        type: 'text',
        locked: false,
        scope: 'template-fixed',
        x: 642,
        y: 82,
        width: 80,
        height: 24,
        textBinding: 'presentation.code',
        style: {
          fontFamily: FONT_NANUM_SQUARE_BOLD,
          fontSize: 10,
          fontWeight: 700,
          lineHeight: 1.2,
          letterSpacing: 0,
          textAlign: 'right',
          color: '#334155',
        },
      },
      {
        id: 'speaker_thread_page_number',
        type: 'text',
        locked: true,
        scope: 'global-fixed',
        x: 670,
        y: 1072,
        width: 50,
        height: 20,
        textBinding: 'page.number',
        style: {
          fontFamily: FONT_NANUM_SQUARE_BOLD,
          fontSize: 10,
          fontWeight: 700,
          lineHeight: 1.2,
          letterSpacing: 0,
          textAlign: 'right',
          color: '#334155',
        },
      },
    ],
    contentZones: createSpeakerThreadZones(),
    slotSchema: SPEAKER_THREAD_SLOT_SCHEMA,
  },
];

const textRunsToPlain = (runs: TextRun[]) => runs.map((run) => run.text).join('');

export const createInitialPublishingDocument = (documentId: string): PublishingDocument => {
  const createdAt = now();
  const masters = createDefaultMasters();
  const defaultMasterId = 'master_speaker_thread';
  const defaultMaster = masters.find((master) => master.id === defaultMasterId);

  return {
    id: documentId,
    version: 1,
    meta: {
      title: { ko: '새 간행물 제목', en: 'New Publication' },
      publicationType: 'proceeding',
      status: 'draft',
      locale: 'ko-KR',
      createdAt,
      updatedAt: createdAt,
      presentationTracks: DEFAULT_PRESENTATION_TRACKS,
    },
    layout: {
      pagePreset: A4_VERTICAL_PRESET,
      pageNumbering: {
        enabled: true,
        startAt: 1,
        showOnCover: false,
        alignmentPreset: 'right',
        mirrorOnEvenPages: false,
      },
      printGuides: {
        showSafeArea: true,
        showCenterLine: true,
        showContentBounds: true,
        showValidationMarks: false,
        alignmentWarningThresholdPx: 0.75,
      },
    },
    masters: {
      defaultMasterId,
      items: masters,
    },
    pages: [
      {
        id: 'page_001',
        pageNumber: 1,
        masterId: defaultMasterId,
        pageRole: 'body',
        zones: defaultMaster?.contentZones.map((zone) => ({
          zoneId: zone.id,
          blocks: [],
        })) ?? [],
      },
    ],
    threads: [],
    contributions: [],
    toc: {
      items: [],
    },
    assets: [],
  };
};

export const getThreadPlainText = (document: PublishingDocument, threadId: string) =>
  textRunsToPlain(document.threads.find((thread) => thread.id === threadId)?.canonicalText ?? []);
