import {
  ContentZoneTemplate,
  DecorationElement,
  MasterTemplate,
  PublishingDocument,
  TextRun,
} from '@/types/publishing';

const now = () => new Date().toISOString();

export const A4_VERTICAL_PRESET = {
  key: 'A4_VERTICAL' as const,
  widthPx: 794,
  heightPx: 1123,
  widthMm: 210,
  heightMm: 297,
  dpi: 96,
  bleedMm: 0,
  safeMarginPx: {
    top: 48,
    right: 48,
    bottom: 48,
    left: 48,
  },
};

export const createMainBodyZone = (): ContentZoneTemplate => ({
  id: 'body_main',
  name: 'Main Text Flow',
  kind: 'text-flow',
  locked: false,
  scope: 'template-fixed',
  allowOverflowSource: true,
  flowGroupId: 'body_flow',
  flowOrder: 1,
  allowThreadContinuation: true,
  frame: {
    x: 72,
    y: 96,
    width: 650,
    height: 900,
  },
  style: {
    fontFamily: 'Noto Serif KR',
    fontSize: 14,
    fontWeight: 400,
    lineHeight: 1.8,
    letterSpacing: 0,
    textAlign: 'justify',
    color: '#222222',
  },
  constraints: {
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    widowLines: 2,
    orphanLines: 2,
    verticalAlign: 'top',
  },
});

export const createCoverZone = (): ContentZoneTemplate => ({
  id: 'cover_title_zone',
  name: 'Cover Title Zone',
  kind: 'text-flow',
  locked: false,
  scope: 'template-fixed',
  allowOverflowSource: true,
  flowGroupId: 'cover_flow',
  flowOrder: 1,
  allowThreadContinuation: false,
  frame: {
    x: 72,
    y: 220,
    width: 650,
    height: 220,
  },
  style: {
    fontFamily: 'Noto Serif KR',
    fontSize: 30,
    fontWeight: 700,
    lineHeight: 1.4,
    letterSpacing: -0.2,
    textAlign: 'center',
    color: '#111111',
  },
  constraints: {
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    verticalAlign: 'middle',
  },
});

export const createSectionLeadZones = (): ContentZoneTemplate[] => [
  {
    id: 'section_lead_header',
    name: 'Section Lead Header',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'section_lead_flow',
    flowOrder: 1,
    allowThreadContinuation: true,
    frame: {
      x: 72,
      y: 140,
      width: 650,
      height: 180,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 24,
      fontWeight: 700,
      lineHeight: 1.45,
      letterSpacing: -0.2,
      textAlign: 'left',
      color: '#111111',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'middle',
    },
  },
  {
    id: 'section_lead_body',
    name: 'Section Lead Body',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'section_lead_flow',
    flowOrder: 2,
    allowThreadContinuation: true,
    frame: {
      x: 72,
      y: 380,
      width: 650,
      height: 616,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 1.8,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
];

export const createCoverPresetDecorations = (): DecorationElement[] => [
  {
    id: 'cover_title_label',
    type: 'text',
    locked: false,
    scope: 'template-fixed',
    x: 72,
    y: 130,
    width: 650,
    height: 40,
    text: 'Cover',
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 14,
      fontWeight: 700,
      lineHeight: 1.4,
      letterSpacing: 2,
      textAlign: 'center',
      color: '#64748b',
    },
  },
  {
    id: 'cover_title_binding',
    type: 'text',
    locked: false,
    scope: 'template-fixed',
    x: 72,
    y: 470,
    width: 650,
    height: 60,
    textBinding: 'document.title',
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 16,
      fontWeight: 500,
      lineHeight: 1.5,
      letterSpacing: 0.4,
      textAlign: 'center',
      color: '#475569',
    },
  },
  {
    id: 'cover_divider',
    type: 'shape',
    locked: false,
    scope: 'template-fixed',
    x: 247,
    y: 182,
    width: 300,
    height: 2,
    shape: 'line',
    fill: '#cbd5e1',
  },
];

export const createSectionLeadPresetDecorations = (): DecorationElement[] => [
  {
    id: 'section_lead_kicker',
    type: 'text',
    locked: false,
    scope: 'template-fixed',
    x: 72,
    y: 92,
    width: 220,
    height: 26,
    text: 'Section Opening',
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 12,
      fontWeight: 700,
      lineHeight: 1.4,
      letterSpacing: 1.8,
      textAlign: 'left',
      color: '#0f172a',
    },
  },
  {
    id: 'section_lead_divider',
    type: 'shape',
    locked: false,
    scope: 'template-fixed',
    x: 72,
    y: 338,
    width: 650,
    height: 2,
    shape: 'line',
    fill: '#cbd5e1',
  },
  {
    id: 'section_lead_number',
    type: 'text',
    locked: false,
    scope: 'template-fixed',
    x: 640,
    y: 92,
    width: 82,
    height: 32,
    textBinding: 'section.number',
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 24,
      fontWeight: 700,
      lineHeight: 1.2,
      letterSpacing: 0,
      textAlign: 'right',
      color: '#94a3b8',
    },
  },
];

export const createTwoColumnZones = (): ContentZoneTemplate[] => [
  {
    id: 'body_col_left',
    name: 'Left Column',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'two_col_body',
    flowOrder: 1,
    allowThreadContinuation: true,
    frame: {
      x: 72,
      y: 96,
      width: 305,
      height: 900,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 13,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
  {
    id: 'body_col_right',
    name: 'Right Column',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'two_col_body',
    flowOrder: 2,
    allowThreadContinuation: true,
    frame: {
      x: 417,
      y: 96,
      width: 305,
      height: 900,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 13,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
];

export const createPosterSummaryZones = (): ContentZoneTemplate[] => [
  {
    id: 'poster_summary_top',
    name: 'Poster Summary',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'poster_flow',
    flowOrder: 1,
    allowThreadContinuation: true,
    frame: {
      x: 72,
      y: 96,
      width: 650,
      height: 220,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 15,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
  {
    id: 'poster_summary_left',
    name: 'Poster Left',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'poster_flow',
    flowOrder: 2,
    allowThreadContinuation: true,
    frame: {
      x: 72,
      y: 350,
      width: 305,
      height: 646,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 13,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
  {
    id: 'poster_summary_right',
    name: 'Poster Right',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'poster_flow',
    flowOrder: 3,
    allowThreadContinuation: true,
    frame: {
      x: 417,
      y: 350,
      width: 305,
      height: 646,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 13,
      fontWeight: 400,
      lineHeight: 1.75,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
];

export const createPresentationTwoColumnZones = (): ContentZoneTemplate[] => [
  {
    id: 'presentation_intro',
    name: 'Presentation Intro',
    kind: 'text-flow',
    locked: false,
    scope: 'template-fixed',
    allowOverflowSource: true,
    flowGroupId: 'presentation_flow',
    flowOrder: 1,
    allowThreadContinuation: true,
    frame: {
      x: 72,
      y: 96,
      width: 650,
      height: 150,
    },
    style: {
      fontFamily: 'Noto Serif KR',
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 1.7,
      letterSpacing: 0,
      textAlign: 'justify',
      color: '#222222',
    },
    constraints: {
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
      widowLines: 2,
      orphanLines: 2,
      verticalAlign: 'top',
    },
  },
  ...createTwoColumnZones().map((zone, index) => ({
    ...zone,
    id: index === 0 ? 'presentation_left' : 'presentation_right',
    name: index === 0 ? 'Presentation Left' : 'Presentation Right',
    flowGroupId: 'presentation_flow',
    flowOrder: index + 2,
    frame: {
      ...zone.frame,
      y: 280,
      height: 716,
    },
  })),
];

export const createDefaultMasters = (): MasterTemplate[] => [
  {
    id: 'master_cover',
    name: 'Cover Master',
    scope: 'global',
    locked: true,
    background: {
      fill: '#ffffff',
      image: null,
    },
    decorations: [
      {
        id: 'cover_page_number',
        type: 'text',
        locked: true,
        scope: 'global-fixed',
        x: 372,
        y: 1072,
        width: 50,
        height: 20,
        textBinding: 'page.number',
      },
    ],
    contentZones: [createCoverZone()],
  },
  {
    id: 'master_body',
    name: 'Body Master',
    scope: 'global',
    locked: true,
    background: {
      fill: '#ffffff',
      image: null,
    },
    decorations: [
      {
        id: 'header_line',
        type: 'shape',
        locked: true,
        scope: 'global-fixed',
        x: 48,
        y: 48,
        width: 698,
        height: 1,
        shape: 'line',
        fill: '#d0d0d0',
      },
      {
        id: 'body_page_number',
        type: 'text',
        locked: true,
        scope: 'global-fixed',
        x: 372,
        y: 1072,
        width: 50,
        height: 20,
        textBinding: 'page.number',
      },
    ],
    contentZones: [createMainBodyZone()],
  },
  {
    id: 'master_two_column',
    name: 'Two Column Master',
    scope: 'global',
    locked: true,
    background: {
      fill: '#ffffff',
      image: null,
    },
    decorations: [
      {
        id: 'two_column_header_line',
        type: 'shape',
        locked: true,
        scope: 'global-fixed',
        x: 48,
        y: 48,
        width: 698,
        height: 1,
        shape: 'line',
        fill: '#d0d0d0',
      },
      {
        id: 'two_column_page_number',
        type: 'text',
        locked: true,
        scope: 'global-fixed',
        x: 372,
        y: 1072,
        width: 50,
        height: 20,
        textBinding: 'page.number',
      },
    ],
    contentZones: createTwoColumnZones(),
  },
];

const textRunsToPlain = (runs: TextRun[]) => runs.map((run) => run.text).join('');

export const createInitialPublishingDocument = (documentId: string): PublishingDocument => {
  const createdAt = now();
  const coverRuns: TextRun[] = [{ text: '새 간행물 제목', marks: { bold: true } }];
  const bodyRuns: TextRun[] = [{ text: '이곳에서 출판용 원고를 작성하고 자동 페이지 분할 결과를 확인할 수 있습니다.' }];
  const masters = createDefaultMasters();

  return {
    id: documentId,
    version: 1,
    meta: {
      title: { ko: '새 간행물 제목', en: 'New Publication' },
      publicationType: 'proceeding',
      status: 'draft',
      locale: 'ko-KR',
      createdAt,
      updatedAt: createdAt,
    },
    layout: {
      pagePreset: A4_VERTICAL_PRESET,
      pageNumbering: {
        enabled: true,
        startAt: 1,
        showOnCover: false,
        alignmentPreset: 'center',
        mirrorOnEvenPages: false,
      },
      printGuides: {
        showSafeArea: true,
        showCenterLine: true,
        showContentBounds: true,
        showValidationMarks: false,
        alignmentWarningThresholdPx: 0.75,
      },
    },
    masters: {
      defaultMasterId: 'master_body',
      items: masters,
    },
    pages: [
      {
        id: 'page_001',
        pageNumber: 1,
        masterId: 'master_cover',
        pageRole: 'cover',
        zones: [
          {
            zoneId: 'cover_title_zone',
            blocks: [
              {
                id: 'block_cover_title_001',
                type: 'text',
                semanticRole: 'title',
                locked: false,
                scope: 'page-editable',
                visible: true,
                flow: {
                  sourceThreadId: 'thread_cover_title',
                  segmentIndex: 0,
                  isContinuation: false,
                  isTerminal: true,
                },
                content: { runs: coverRuns },
                ebook: {
                  include: true,
                  toc: {
                    enabled: false,
                  },
                },
              },
            ],
          },
        ],
      },
      {
        id: 'page_002',
        pageNumber: 2,
        masterId: 'master_body',
        pageRole: 'body',
        zones: [
          {
            zoneId: 'body_main',
            blocks: [
              {
                id: 'block_body_001_seg_000',
                type: 'text',
                semanticRole: 'paragraph',
                locked: false,
                scope: 'page-editable',
                visible: true,
                flow: {
                  sourceThreadId: 'thread_body_main',
                  segmentIndex: 0,
                  isContinuation: false,
                  isTerminal: true,
                },
                content: { runs: bodyRuns },
                ebook: {
                  include: true,
                  toc: {
                    enabled: false,
                  },
                },
              },
            ],
          },
        ],
      },
    ],
    threads: [
      {
        id: 'thread_cover_title',
        type: 'text-flow',
        canonicalText: coverRuns,
        semanticRole: 'title',
        ebook: {
          include: true,
          toc: {
            enabled: false,
          },
        },
        originBlockId: 'block_cover_title_001',
        sourceZoneId: 'cover_title_zone',
        sourcePageId: 'page_001',
        zoneSequence: [{ pageId: 'page_001', zoneId: 'cover_title_zone' }],
      },
      {
        id: 'thread_body_main',
        type: 'text-flow',
        canonicalText: bodyRuns,
        semanticRole: 'paragraph',
        ebook: {
          include: true,
          toc: {
            enabled: false,
          },
        },
        originBlockId: 'block_body_001_seg_000',
        sourceZoneId: 'body_main',
        sourcePageId: 'page_002',
        zoneSequence: [{ pageId: 'page_002', zoneId: 'body_main' }],
      },
    ],
    toc: {
      items: [],
    },
    assets: [],
  };
};

export const getThreadPlainText = (document: PublishingDocument, threadId: string) =>
  textRunsToPlain(document.threads.find((thread) => thread.id === threadId)?.canonicalText ?? []);
